name: Run Python Training Script (Sesuai Materi)

on:
  push:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'
      
      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 pandas scikit-learn

      # 4. JALANKAN SKRIPNYA LANGSUNG
      - name: Run Python Training Script
        run: |
          cd MLProject  # Masuk ke folder MLProject
          python modelling.py # Jalankan skripnya!

      # 5. Upload Artefak
      - name: Upload model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: MLProject/mlruns/